/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://wtsng2cz4l.execute-api.us-west-2.amazonaws.com/production",
            "region": "us-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://2v3spdyivbcz3dtefcfnq7kx4a.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-west-2:8c7be667-b427-42ca-ad6e-47fef4724c7c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_l58Kk5WR7",
    "aws_user_pools_web_client_id": "4oqunrcr6ativ73a8k6qbtdeec",
    "oauth": {
        "domain": "sensiebackend-production.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://joinsensie.com/dashboard/,sensie://callback/,http://localhost:3000/dashboard/",
        "redirectSignOut": "https://joinsensie.com/dashboard/,sensie://,http://localhost:3000/dashboard/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "sensiecontent409a7-production",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "54f86bc6b03c4cd38161e8b36615d973",
            "region": "us-west-2"
        }
    }
};


export default awsmobile;
