/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://7z3aehem00.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://2ueiebfuvrbzlnaijnbdzve5oy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-west-2:84b30b71-e50b-4c26-b61d-956b2fe06657",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_eA1Iz4yK5",
    "aws_user_pools_web_client_id": "3adnmq72avbn5b35bua8afdbop",
    "oauth": {
        "domain": "sensiebackend-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.joinsensie.com/dashboard/,sensie://callback/,http://localhost:3000/dashboard/",
        "redirectSignOut": "https://dev.joinsensie.com/dashboard/,sensie://,http://localhost:3000/dashboard/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "sensiecontent223927-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "54f86bc6b03c4cd38161e8b36615d973",
            "region": "us-west-2"
        }
    }
};


export default awsmobile;
